import type { CSSProperties, ReactNode } from 'react';
import { ArrowUpRight, ArrowRight, MapPin, Phone, Clock, Menu, X, Camera, MessageCircle, Star, Sparkles, Scissors } from 'lucide-react';
import { useState } from 'react';
import { BRAND_NAME } from '../../lib/brand';
import type { PublicSite, Service, WebsiteSectionType } from '../../types/domain';
import { isBarberBusiness, templateFor, safeImage, safeLink, whatsappLink } from './templates';
import './site.css';
import { BarberArt, BarberRibbon } from './BarberArt';
const text=(c:Record<string,unknown>,key:string,fallback='')=>typeof c[key]==='string'?c[key] as string:fallback;
const list=(c:Record<string,unknown>,key:string):Array<Record<string,unknown>>=>Array.isArray(c[key])?(c[key] as unknown[]).filter((x):x is Record<string,unknown>=>!!x&&typeof x==='object'):[];
const money=(n:number)=>new Intl.NumberFormat('es-PE',{style:'currency',currency:'PEN',maximumFractionDigits:2}).format(n);
const days=['Domingo','Lunes','Martes','Miércoles','Jueves','Viernes','Sábado'];
export function SiteArt({small=false}:{small?:boolean}) { return <div className={`nw-art ${small?'nw-art-small':''}`} aria-hidden="true"><div className="nw-art-halo"/><div className="nw-art-sculpture"/><div className="nw-art-orbit"/><span className="nw-art-star">✳</span></div>; }
export default function SiteRenderer({site,preview=false,onBook}:{site:PublicSite;preview?:boolean;onBook:(service?:Service)=>void}) {
 const barber=isBarberBusiness(site.business.type);
 const t=templateFor(site);const [menu,setMenu]=useState(false);
 const accent=/^#[\da-f]{6}$/i.test(site.branding.colors.primary??'')?site.branding.colors.primary!:t.accent;
 const button=/^#[\da-f]{6}$/i.test(site.branding.colors.button??'')?site.branding.colors.button!:accent;
 const contrast=(hex:string)=>{const values=hex.slice(1).match(/../g)!.map(x=>parseInt(x,16)/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);return values[0]!*.2126+values[1]!*.7152+values[2]!*.0722>.179?'#151915':'#ffffff';};
 const style={'--nw-accent':accent,'--nw-accent-ink':contrast(accent),'--nw-button':button,'--nw-button-ink':contrast(button),'--nw-heading':site.branding.font_key==='sans'?'"Inter", system-ui, sans-serif':'"Playfair Display", Georgia, serif'} as CSSProperties;
 const sections=site.sections.filter(s=>s.active).sort((a,b)=>a.position-b.position);
 const wa=whatsappLink(site.business.whatsapp||site.business.phone);
 const logo=safeImage(site.branding.logo_url);
 const scroll=(node:HTMLElement,id:string)=>{node.ownerDocument.getElementById(`nw-${id}`)?.scrollIntoView({behavior:node.ownerDocument.defaultView?.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});setMenu(false);};
 const book=(label='Reservar mi cita',service?:Service)=> <button className="nw-button" onClick={()=>onBook(service)} >{label}<ArrowUpRight size={17}/></button>;
 const heading=(content:Record<string,unknown>,number:string)=><div className="nw-section-heading"><span className="nw-kicker">{number} / {site.business.name}</span><h2>{text(content,'title')}</h2>{text(content,'subtitle')&&<p>{text(content,'subtitle')}</p>}</div>;
 const image=(url:unknown,alt:string,className='')=>safeImage(url)?<img className={className} src={safeImage(url)} alt={alt} loading="lazy" decoding="async"/>:null;
 const renders:Record<WebsiteSectionType,(c:Record<string,unknown>)=>ReactNode>={
 HERO:c=><section className="nw-hero nw-section" id="nw-HERO"><div className="nw-hero-content"><p className="nw-kicker"><span className="nw-dot"/>{text(c,'eyebrow',site.website.tagline||(barber?'Barbería · Oficio y estilo':'Belleza & bienestar'))}</p><h1>{text(c,'title',site.business.name)}</h1><p className="nw-hero-description">{text(c,'subtitle',site.business.description)}</p><div className="nw-hero-actions">{c.cta_enabled!==false&&book(text(c,'cta','Reservar mi cita'))}<button className="nw-text-link" onClick={e=>scroll(e.currentTarget,'SERVICES')}>Explorar servicios <ArrowRight size={16}/></button></div><div className="nw-hero-note"><span className="nw-mini-star">{barber?<Scissors size={28}/>:"✳"}</span><span>{site.website.tagline||(barber?'Tu corte. Tu carácter. Tu barbería.':'Tu espacio. Tu estilo. Tu momento.')}</span></div></div><div className="nw-hero-visual">{safeImage(c.image_url||site.branding.cover_url)?<img className="nw-cover" src={safeImage(c.image_url||site.branding.cover_url)} alt={text(c,'image_alt',site.business.name)} fetchPriority="high"/>:(barber?<BarberArt/>:<SiteArt/>)}<span className="nw-visual-caption">{text(c,'image_caption',barber?'El oficio de crear estilo.':'El arte de cuidarte.')}</span></div><span className="nw-hero-index" aria-hidden="true">{barber?"01 — Corte y carácter":"01 — Un nuevo comienzo"}</span>{barber&&<BarberRibbon/>}</section>,
 SERVICES:c=><section className="nw-section nw-services" id="nw-SERVICES">{heading(c,'02')}<div className="nw-services-grid">{site.services.filter(s=>!(Array.isArray(c.hidden_ids)&&c.hidden_ids.includes(s.id))).map((s,i)=><article className="nw-service nw-reveal" key={s.id} style={{animationDelay:`${i*.06}s`}}><span className="nw-service-no">{String(i+1).padStart(2,'0')}</span><div><h3>{s.name}</h3><p>{s.description}</p><span className="nw-service-duration"><Clock size={13}/>{s.durationMin} min</span></div><div className="nw-service-end"><strong>{money(s.price)}</strong><button aria-label={`Reservar ${s.name}`} onClick={()=>onBook(s)}><ArrowUpRight size={20}/></button></div></article>)}</div>{!site.services.length&&<p className="nw-empty">{preview?'Crea servicios visibles en el módulo Servicios para mostrarlos aquí.':'Pulsa Reservar para consultar los servicios y horarios disponibles.'}</p>}</section>,
 ABOUT:c=><section className="nw-section nw-about" id="nw-ABOUT"><div className="nw-about-visual">{safeImage(c.image_url)?image(c.image_url,text(c,'image_alt','Nuestro espacio')):(barber?<BarberArt/>:<SiteArt/>)}<span className="nw-about-stamp">{barber?<Scissors size={35}/>:"✳"}<small>{site.business.name}</small></span></div><div>{heading(c,'03')}<p className="nw-prose">{text(c,'body',site.business.description)}</p><div className="nw-signature">{site.business.name}<ArrowUpRight size={28}/></div></div></section>,
 GALLERY:c=>{const images=list(c,'images').filter(x=>safeImage(x.url));return images.length||preview?<section className="nw-section nw-gallery" id="nw-GALLERY">{heading(c,'04')}<div className="nw-gallery-grid">{images.map((x,i)=><figure className="nw-reveal" key={`${x.url}-${i}`}>{image(x.url,text(x,'alt',`Galería ${i+1}`))}{text(x,'alt')&&<figcaption>{text(x,'alt')}</figcaption>}</figure>)}</div>{!images.length&&<p className="nw-empty">Agrega tus fotografías en Galería. No se publican imágenes de demostración.</p>}</section>:null;},
 TEAM:c=><section className="nw-section nw-team" id="nw-TEAM">{heading(c,'05')}<div className="nw-team-grid">{site.team.filter(e=>!(Array.isArray(c.hidden_ids)&&c.hidden_ids.includes(e.id))).map(e=><article key={e.id} className="nw-team-card nw-reveal"><div className="nw-team-photo">{safeImage(e.photoUrl)?image(e.photoUrl,e.fullName):<span>{e.fullName.split(' ').map(x=>x[0]).slice(0,2).join('')}</span>}</div><h3>{e.fullName}</h3><p>{e.roleLabel}</p>{e.specialty&&<small>{e.specialty}</small>}</article>)}</div>{!site.team.length&&<p className="nw-empty">{preview?'Elige miembros visibles en el módulo Equipo.':'Conoce a nuestro equipo durante tu visita.'}</p>}</section>,
 PROMOTIONS:c=>site.promotions.length||preview?<section className="nw-section nw-promotions" id="nw-PROMOTIONS">{heading(c,'06')}<div className="nw-promotions-grid">{site.promotions.map((p,i)=><article key={i}><Sparkles size={25}/><h3>{p.name}</h3><p>{p.description}</p><strong>{p.price!=null?money(p.price):p.discount_percent?`${p.discount_percent}% de descuento`:''}</strong>{book('Reservar')}</article>)}</div>{!site.promotions.length&&<p className="nw-empty">Tus promociones activas y visibles de Fidelización aparecerán aquí.</p>}</section>:null,
 TESTIMONIALS:c=>{const reviews=Array.isArray(c.items)?list(c,'items'):site.testimonials;return reviews.length||preview?<section className="nw-section nw-testimonials" id="nw-TESTIMONIALS">{heading(c,'07')}<div className="nw-reviews-grid">{reviews.map((r,i)=><figure key={i}><div className="nw-stars" aria-label={`${Math.max(1,Math.min(5,Number(r.rating)||5))} estrellas`}>{Array.from({length:Math.max(1,Math.min(5,Number(r.rating)||5))},(_,j)=><Star key={j} size={15} fill="currentColor"/>)}</div><blockquote>“{String(r.content||'')}”</blockquote><figcaption>{String(r.author_name||'')}</figcaption></figure>)}</div>{!reviews.length&&<p className="nw-empty">Agrega testimonios auténticos, con autorización de tus clientes.</p>}</section>:null;},
 LOCATION:c=><section className="nw-section nw-location" id="nw-LOCATION"><div>{heading(c,'08')}<address>{site.business.address&&<p><MapPin size={19}/>{site.business.address}</p>}{site.business.phone&&<p><Phone size={19}/><a href={`tel:${site.business.phone.replace(/[^+\d]/g,'')}`}>{site.business.phone}</a></p>}{site.business.email&&<p><a href={`mailto:${site.business.email.replace(/[\r\n]/g,'')}`}>{site.business.email}</a></p>}</address><div className="nw-hours">{site.hours.map((h,i)=><div key={`${h.weekday}-${i}`}><span>{days[h.weekday]}</span><span>{h.is_closed?'Cerrado':`${h.open_time?.slice(0,5)} – ${h.close_time?.slice(0,5)}`}</span></div>)}</div>{wa&&<a className="nw-text-link" href={wa} target="_blank" rel="noopener noreferrer"><MessageCircle size={17}/> Hablemos por WhatsApp <ArrowUpRight size={15}/></a>}</div><div className="nw-map">{site.website.map_query||site.business.address?<><iframe title={`Ubicación de ${site.business.name}`} src={`https://maps.google.com/maps?q=${encodeURIComponent(site.website.map_query||site.business.address)}&output=embed`} loading="lazy" referrerPolicy="no-referrer-when-downgrade" allowFullScreen/><a href={`https://maps.google.com/?q=${encodeURIComponent(site.website.map_query||site.business.address)}`} target="_blank" rel="noopener noreferrer">Abrir en Google Maps <ArrowUpRight size={15}/></a></>:<div className="nw-empty"><MapPin size={32}/><p>Configura tu dirección para mostrar el mapa.</p></div>}</div></section>,
 CTA:c=><section className="nw-section nw-cta" id="nw-CTA"><span className="nw-cta-star" aria-hidden="true">✳</span><p className="nw-kicker">{barber?"Tu próxima visita a la barbería":"Tu próximo momento favorito"}</p><h2>{text(c,'title','¿Nos vemos pronto?')}</h2>{text(c,'body')&&<p>{text(c,'body')}</p>}{book(text(c,'cta','Reservar mi cita'))}</section>,
 FOOTER:c=><footer className="nw-section nw-footer" id="nw-FOOTER"><div className="nw-footer-top"><div><strong className="nw-footer-brand">{site.business.name}</strong><p>{text(c,'text',site.website.tagline)}</p></div><div className="nw-socials">{Object.entries(site.website.socials).filter(([,url])=>safeLink(url)).map(([name,url])=><a key={name} href={safeLink(url)} target="_blank" rel="noopener noreferrer">{name==='instagram'&&<Camera size={16}/>} {name}<ArrowUpRight size={14}/></a>)}</div></div><div className="nw-footer-bottom"><span>© {new Date().getFullYear()} {site.business.name}</span><span>Hecho con {BRAND_NAME}</span></div></footer>,
 };
 return <div className={`nuvia-site nw-${t.key.toLowerCase()}${barber?" nw-barber":""}`} style={style} data-template={t.key} data-industry={barber?"BARBERSHOP":undefined}><nav className="nw-nav"><a className="nw-brand" href="#" onClick={e=>{e.preventDefault();scroll(e.currentTarget,'HERO');}}>{logo&&<img src={logo} alt=""/>}<span>{site.business.name}</span></a><div className={`nw-nav-links ${menu?'is-open':''}`}>{(['SERVICES','ABOUT','GALLERY','LOCATION'] as const).filter(type=>sections.some(s=>s.type===type)).map(type=><button key={type} onClick={e=>scroll(e.currentTarget,type)}>{{SERVICES:'Servicios',ABOUT:'Nosotros',GALLERY:'Galería',LOCATION:'Encuéntranos'}[type]}</button>)}</div><div className="nw-nav-actions">{book('Reservar')}<button className="nw-menu" aria-label={menu?'Cerrar navegación':'Abrir navegación'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X size={21}/>:<Menu size={21}/>}</button></div></nav><main>{sections.map(s=><div key={s.type}>{renders[s.type]?.(s.content)}</div>)}</main>{wa&&!preview&&<a className="nw-whatsapp" href={wa} target="_blank" rel="noopener noreferrer" aria-label="Contactar por WhatsApp"><MessageCircle size={23}/></a>}</div>;
}
