import { useEffect, useRef, useState, type Dispatch } from 'react';
import { ArrowRight, Bot, CalendarDays, Check, Gift, Globe, HardDrive, MessageCircle, Plus, Send, ShieldCheck, Sparkles, Trash2, Users, X } from 'lucide-react';
import { DEMOS, demoServices } from './data';
import { DEMO_STARTER, DEMO_REWARD_COST, DEMO_STORAGE_LIMIT, storageMB, type DemoView } from './starter-plan';
import { demoClients, demoEarned, demoPoints, demoReward, demoStorageBytes, monthlyAppointments, type DemoAction, type DemoState } from './starter-state';
import './starter.css';
type Props={state:DemoState;dispatch:Dispatch<DemoAction>;navigate:(view:DemoView)=>void};
const FEATURES=[['website','Página web',Globe],['loyalty','Fidelización',Gift],['ai','Copiloto IA',Bot],['whatsapp','WhatsApp',MessageCircle]] as const;
export function StarterSummary({state,navigate}:Pick<Props,'state'|'navigate'>){
 return <section className="nd-starter-summary" aria-label="Funciones incluidas en la demo Starter"><div><span className="nd-soft-tag">DEMO STARTER</span><h2>Todo lo esencial para empezar.</h2><p>Hasta {DEMO_STARTER.maxWorkers} trabajadores · {DEMO_STARTER.maxMonthlyAppointments} citas mensuales · {DEMO_STARTER.maxStorageMb} MB</p></div><div className="nd-starter-shortcuts">{FEATURES.map(([view,label,Icon])=><button key={view} onClick={()=>navigate(view)}><Icon size={15}/>{label}<Check size={12}/></button>)}<span><X size={13}/> Sin multisucursal</span><button onClick={()=>navigate('plan')}>Ver plan y consumo <ArrowRight size={14}/></button></div><span className="nd-starter-mini-usage">{state.workers.length}/{DEMO_STARTER.maxWorkers} trabajadores · {monthlyAppointments(state,state.today)}/{DEMO_STARTER.maxMonthlyAppointments} citas este mes</span></section>;
}
export function StarterPlan({state,dispatch,navigate}:Props){
 const bytes=demoStorageBytes(state),used=monthlyAppointments(state,state.today);
 return <><div className="nd-page-title"><div><span className="nd-eyebrow">EL PUNTO DE PARTIDA DE TU NEGOCIO</span><h1>Plan Starter</h1><p>Para negocios que están comenzando a digitalizar su operación.</p></div><span className="nd-soft-tag">Plan de esta demostración</span></div>
 <div className="nd-starter-plan-grid"><section className="nd-card nd-plan-inclusions"><span className="nd-eyebrow">INCLUIDO EN AMBAS DEMOS</span><h2>Pequeño equipo.<br/>Grandes posibilidades.</h2><ul><li><Users size={18}/><strong>Hasta {DEMO_STARTER.maxWorkers} trabajadores</strong></li><li><CalendarDays size={18}/><strong>{DEMO_STARTER.maxMonthlyAppointments} citas mensuales</strong></li><li><HardDrive size={18}/><strong>{DEMO_STARTER.maxStorageMb} MB de almacenamiento</strong></li>{FEATURES.map(([view,label])=><li key={view}><Check size={18}/><button onClick={()=>navigate(view)}>{label}<ArrowRight size={15}/></button></li>)}<li className="nd-not-included"><X size={18}/><span>Multisucursal: no incluido</span></li></ul><p>Una sola sucursal. Esta demo no ofrece creación ni cambio de sucursales.</p></section>
 <section className="nd-card nd-plan-consumption"><span className="nd-eyebrow">CAPACIDAD Y USO DE LA DEMO</span><h2>Tu espacio para crecer</h2>{[
 {label:'Trabajadores',value:state.workers.length,max:DEMO_STARTER.maxWorkers,text:`${state.workers.length} / ${DEMO_STARTER.maxWorkers}`,view:'services' as const},
 {label:'Citas del mes',value:used,max:DEMO_STARTER.maxMonthlyAppointments,text:`${used} / ${DEMO_STARTER.maxMonthlyAppointments}`,view:'agenda' as const},
 {label:'Almacenamiento',value:bytes,max:DEMO_STORAGE_LIMIT,text:`${storageMB(bytes)} / ${DEMO_STARTER.maxStorageMb} MB`,view:'plan' as const},
 ].map(item=><div className="nd-capacity" key={item.label}><div><button onClick={()=>navigate(item.view)}>{item.label}<ArrowRight size={13}/></button><strong>{item.text}</strong></div><div className="nd-capacity-track" role="progressbar" aria-label={item.label} aria-valuenow={item.value} aria-valuemin={0} aria-valuemax={item.max}><span style={{width:`${Math.min(100,item.value/item.max*100)}%`}}/></div></div>)}<div className="nd-capacity-note"><ShieldCheck size={20}/><p>Los límites se aplican a las acciones de esta demo. Las citas canceladas sin atender liberan cupo; las atendidas siguen contando. Las citas de otro mes usan su propio cupo.</p></div><p className="nd-muted-note">Consumo del mes {state.today.slice(0,7)}. No cambia tu suscripción ni los datos reales.</p></section></div>
 <section className="nd-card nd-demo-files"><div className="nd-section-title"><div><span className="nd-eyebrow">ALMACENAMIENTO STARTER</span><h2>Archivos de demostración</h2></div><span className="nd-soft-tag">{DEMO_STARTER.maxStorageMb} MB</span></div><p>Prueba la capacidad con imágenes JPG, PNG o WebP. Solo conservamos nombre y tamaño en memoria: no se suben ni se leen sus contenidos.</p><label className="nd-file-picker"><Plus size={17}/><span>Añadir archivos a la demo</span><input aria-label="Añadir archivos a la demo" type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={e=>{const files=Array.from(e.target.files??[]).map(f=>({id:`demo-file-${crypto.randomUUID()}`,name:f.name,size:f.size,type:f.type}));dispatch({type:'ADD_FILES',files});e.target.value='';}}/></label><div className="nd-files-list">{state.files.map(f=><div key={f.id}><HardDrive size={18}/><div><strong>{f.name}</strong><small>{f.builtin?'Recurso visual incluido':'Solo nombre y tamaño · No subido'}</small></div><span>{storageMB(f.size)}</span>{!f.builtin&&<button aria-label={`Quitar archivo demo ${f.name}`} onClick={()=>dispatch({type:'REMOVE_FILE',id:f.id})}><Trash2 size={16}/></button>}</div>)}</div></section></>;
}
export function DemoTeamAdd({state,dispatch}:Pick<Props,'state'|'dispatch'>){
 const [name,setName]=useState('');const full=state.workers.length>=DEMO_STARTER.maxWorkers;
 return <div className="nd-card nd-team-add"><div><span className="nd-soft-tag">{state.workers.length} / {DEMO_STARTER.maxWorkers} trabajadores</span><p>Starter permite hasta {DEMO_STARTER.maxWorkers} trabajadores. Los profesionales de esta demo atienden el catálogo de ejemplo.</p></div><form onSubmit={e=>{e.preventDefault();dispatch({type:'ADD_WORKER',name});if(name.trim().length>=2&&!state.workers.some(w=>w.toLocaleLowerCase('es')===name.trim().toLocaleLowerCase('es'))&&!full)setName('');}}><label>Nombre ficticio del trabajador<input aria-label="Nombre ficticio del trabajador" value={name} maxLength={80} disabled={full} placeholder="Nombre de ejemplo" onChange={e=>setName(e.target.value)}/></label><button className="nd-primary" type="submit" disabled={full||name.trim().length<2}><Plus size={16}/>Añadir trabajador demo</button></form>{full&&<p role="status">Llegaste al límite de {DEMO_STARTER.maxWorkers} trabajadores de Starter. Business permite un equipo mayor en negocios reales.</p>}</div>;
}
export function DemoLoyalty({state,dispatch}:Pick<Props,'state'|'dispatch'>){
 const clients=demoClients(state);const [selected,setSelected]=useState(clients[0]!);const [pending,setPending]=useState<{id:string;customer:string}|null>(null);
 const earned=demoEarned(state,selected),points=demoPoints(state,selected),redemptions=state.redemptions.filter(r=>r.customer===selected);
 return <><div className="nd-page-title"><div><span className="nd-eyebrow">MOTIVOS PARA VOLVER</span><h1>Fidelización</h1><p>Puntos, recompensas e historial. Incluido en Starter para ambas demos.</p></div><span className="nd-soft-tag"><Gift size={13}/> Lealtad en acción</span></div>
 <div className="nd-loyalty-grid"><section className="nd-card nd-loyalty-account"><label>Cliente de ejemplo<select aria-label="Cliente de fidelización" value={selected} onChange={e=>{setSelected(e.target.value);setPending(null);}}>{clients.map(name=><option key={name}>{name}</option>)}</select></label><span className="nd-eyebrow">PUNTOS DISPONIBLES</span><strong className="nd-points" data-testid="demo-loyalty-balance">{points}<small>puntos demo</small></strong><div className="nd-loyalty-totals"><span>{earned} acumulados</span><span>{earned-points} canjeados</span></div><p>Ejemplo: cada sol de una venta simulada suma un punto. Registra una venta en Ventas y verás el saldo actualizado aquí y en Clientes.</p></section>
 <section className="nd-card nd-reward"><span className="nd-reward-icon"><Gift size={30}/></span><span className="nd-eyebrow">UNA RECOMPENSA DE EJEMPLO</span><h2>{demoReward(state.kind)}</h2><p>Beneficio ficticio para mostrar cómo tus clientes pueden usar sus puntos. No genera un descuento ni un servicio real.</p><strong>{DEMO_REWARD_COST} puntos demo</strong>{pending?<div className="nd-redeem-confirm"><p>¿Canjear {DEMO_REWARD_COST} puntos de {pending.customer}?</p><div><button className="nd-primary" onClick={()=>{dispatch({type:'REDEEM',...pending});setPending(null);}}>Confirmar canje demo</button><button className="nd-secondary" onClick={()=>setPending(null)}>Volver</button></div></div>:<button className="nd-primary" disabled={points<DEMO_REWARD_COST} onClick={()=>setPending({id:`demo-reward-${crypto.randomUUID()}`,customer:selected})}>Simular canje</button>}{points<DEMO_REWARD_COST&&<small>Se necesitan {DEMO_REWARD_COST} puntos. El saldo nunca puede quedar negativo.</small>}</section></div>
 <section className="nd-card nd-loyalty-history"><div className="nd-section-title"><h2>Movimientos de {selected}</h2><span className="nd-soft-tag">Solo demostración</span></div>{redemptions.map(r=><div key={r.id}><Gift size={18}/><span>{r.reward}<small>Canje de demostración</small></span><strong>−{r.points} puntos</strong></div>)}{state.appointments.filter(a=>a.customer===selected&&a.paid).map(a=><div key={a.id}><Check size={18}/><span>{demoServices(state.kind).find(s=>s.id===a.serviceId)?.name}<small>Venta demo · {a.day}</small></span><strong>+{Math.floor(demoServices(state.kind).find(s=>s.id===a.serviceId)?.price??0)} puntos</strong></div>)}{!earned&&!redemptions.length&&<p className="nd-empty">Este cliente aún no tiene movimientos demo.</p>}</section></>;
}
const PROMPTS=['Resume mi negocio','¿Qué servicio se vende más?','Ayúdame a llenar la agenda','Redacta un recordatorio'];
export function DemoCopilot({state,dispatch,navigate}:Props){
 const [question,setQuestion]=useState('');const feed=useRef<HTMLDivElement>(null);const id=useRef(crypto.randomUUID());
 useEffect(()=>{if(feed.current)feed.current.scrollTop=feed.current.scrollHeight;},[state.chat.length]);
 const ask=(text:string,requestId=crypto.randomUUID())=>{if(!text.trim())return;dispatch({type:'ASK',id:requestId,question:text});setQuestion('');};
 return <><div className="nd-page-title"><div><span className="nd-eyebrow">UN COPILOTO PARA TU NEGOCIO</span><h1>Copiloto IA</h1><p>Explora Nuvia IA con preguntas sobre los datos ficticios de {DEMOS[state.kind].name}.</p></div><span className="nd-soft-tag">Incluido en Starter</span></div><section className="nd-card nd-ai-panel"><div className="nd-ai-header"><span><Sparkles size={24}/></span><div><h2>Nuvia IA</h2><p>Modo demo: respuestas guiadas, sin conexión a un modelo de IA.</p></div></div><div className="nd-ai-prompts">{PROMPTS.map(prompt=><button key={prompt} onClick={()=>ask(prompt)}><Sparkles size={14}/>{prompt}</button>)}</div><div ref={feed} className="nd-ai-feed" role="log" aria-label="Conversación de demostración" aria-live="polite">{!state.chat.length?<div className="nd-ai-welcome"><Bot size={42}/><h3>¿Qué te gustaría revisar?</h3><p>Consulta la agenda, las ventas o una idea para fidelizar. Las respuestas calculadas cambian cuando modificas esta demo.</p></div>:state.chat.map(item=><div key={item.id}><div className="nd-chat-question"><span>Tú</span><p>{item.question}</p></div><div className="nd-chat-answer"><span><Sparkles size={13}/>Nuvia IA · respuesta de demostración</span><p>{item.answer}</p></div></div>)}</div><form className="nd-ai-input" onSubmit={e=>{e.preventDefault();ask(question,id.current);}}><label className="sr-only" htmlFor="demo-ai-question">Pregunta para Nuvia IA demo</label><input id="demo-ai-question" value={question} maxLength={600} placeholder="Prueba: resume mi negocio…" onChange={e=>{setQuestion(e.target.value);id.current=crypto.randomUUID();}}/><button className="nd-primary" aria-label="Consultar Nuvia IA demo" disabled={!question.trim()}><Send size={17}/></button></form><div className="nd-ai-footer"><span>Nuvia IA · No realiza acciones ni utiliza datos reales.</span><button onClick={()=>navigate('whatsapp')}>Probar WhatsApp <ArrowRight size={14}/></button></div></section></>;
}
const TEMPLATES=[['reminder','Recordatorio de cita'],['followup','Seguimiento de atención'],['return','Invitación a volver']] as const;
export function DemoWhatsApp({state,dispatch}:Pick<Props,'state'|'dispatch'>){
 const clients=demoClients(state);const first=state.appointments.find(a=>a.status==='CONFIRMED')?.customer??clients[0]!;
 const [selected,setSelected]=useState(first),[template,setTemplate]=useState<(typeof TEMPLATES)[number][0]>('reminder');
 const templateText=(customer:string,type:typeof template)=>{
  const name=DEMOS[state.kind].name,appointment=state.appointments.find(a=>a.customer===customer&&a.status==='CONFIRMED');
  if(type==='followup')return `Hola, ${customer}. Gracias por visitar ${name}. ¿Cómo te sentiste con tu atención? Nos encantará conocer tu experiencia. [Mensaje de ejemplo]`;
  if(type==='return')return `Hola, ${customer}. En ${name} nos gustaría volver a verte. Elige tu próximo servicio en nuestra página y regálate un momento para ti. [Mensaje de ejemplo]`;
  return appointment?`Hola, ${customer}. Te recordamos tu cita demo en ${name} el ${appointment.day} a las ${appointment.time}. Si necesitas cambiarla, avísanos. [Mensaje de ejemplo]`:`Hola, ${customer}. Cuando reserves tu próxima cita en ${name}, podremos preparar tu recordatorio aquí. [Este cliente no tiene citas demo pendientes]`;
 };
 const [text,setText]=useState(()=>templateText(first,'reminder'));const requestId=useRef(crypto.randomUUID());
 const edit=(value:string)=>{setText(value);requestId.current=crypto.randomUUID();};
 return <><div className="nd-page-title"><div><span className="nd-eyebrow">CERCA DE TUS CLIENTES</span><h1>WhatsApp</h1><p>Prepara recordatorios y seguimientos. Esta demo no se conecta a WhatsApp ni contacta a nadie.</p></div><span className="nd-soft-tag">Incluido en Starter</span></div><div className="nd-whatsapp-grid"><section className="nd-card nd-wa-compose"><h2>Preparar mensaje demo</h2><label>Cliente ficticio<select aria-label="Cliente de WhatsApp demo" value={selected} onChange={e=>{setSelected(e.target.value);edit(templateText(e.target.value,template));}}>{clients.map(name=><option key={name}>{name}</option>)}</select></label><label>Plantilla<select aria-label="Plantilla de WhatsApp demo" value={template} onChange={e=>{const key=e.target.value as typeof template;setTemplate(key);edit(templateText(selected,key));}}>{TEMPLATES.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>Mensaje de ejemplo<textarea aria-label="Mensaje de WhatsApp demo" value={text} maxLength={1000} rows={6} onChange={e=>edit(e.target.value)}/></label><button className="nd-primary" disabled={!text.trim()} onClick={()=>{dispatch({type:'QUEUE',id:requestId.current,customer:selected,text});setText('');}}><MessageCircle size={17}/>Añadir a cola demo</button><p className="nd-muted-note">No hay conexión, número real, cobro ni envío. Los mensajes quedan marcados como «En cola demo · No enviado».</p></section><section className="nd-card nd-wa-preview"><div><MessageCircle size={21}/><strong>{selected}</strong><span>Vista de ejemplo</span></div><div className="nd-wa-preview-area">{text?<div className="nd-wa-bubble">{text}<small>Borrador demo · No enviado</small></div>:<p>Mensaje añadido a la cola de esta demo. Elige otra plantilla para seguir probando.</p>}</div><div className="nd-wa-offline"><ShieldCheck size={15}/>Entorno aislado · Sin conexión a WhatsApp</div></section></div>
 <section className="nd-card nd-automations"><div className="nd-section-title"><div><span className="nd-eyebrow">AUTOMATIZACIONES DE EJEMPLO</span><h2>Cuida cada momento</h2></div><span className="nd-soft-tag">Solo configuración demo</span></div><div>{TEMPLATES.map(([key,label])=><article key={key}><MessageCircle size={19}/><div><h3>{label}</h3><p>{state.automations[key]?'Activada en esta demo':'Desactivada en esta demo'}</p></div><button className="nd-toggle" role="switch" aria-label={`Automatización demo: ${label}`} aria-checked={state.automations[key]} onClick={()=>dispatch({type:'AUTOMATION',key,enabled:!state.automations[key]})}><span/></button></article>)}</div><p className="nd-muted-note">Estos interruptores ilustran la configuración; no programan tareas ni envíos reales.</p></section>
 <section className="nd-card nd-wa-queue"><div className="nd-section-title"><h2>Cola de demostración</h2><span className="nd-soft-tag">{state.messages.length} mensajes</span></div>{state.messages.length?state.messages.map(m=><article key={m.id}><div><strong>{m.customer}</strong><span className="nd-soft-tag">En cola demo · No enviado</span><button aria-label={`Quitar mensaje demo de ${m.customer}`} onClick={()=>dispatch({type:'REMOVE_MESSAGE',id:m.id})}><Trash2 size={16}/></button></div><p>{m.text}</p></article>):<p className="nd-empty">Todavía no hay mensajes en la cola demo. Prepara el primero arriba.</p>}</section></>;
}
